import Cabecalho from '@/components/Cabecalho/Cabecalho'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}
       <Cabecalho />
        {children}
       <Rodape /> 
      </body>
    </html>
  )
}
